---

- name: ensure ufw is installed
  apt:
    name: ufw
    state: installed
    update_cache: yes
    cache_valid_time: 3600

- name: set rules before enabling firewall
  ufw:
    rule: '{{ item.rule|default("allow") }}'
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
    delete: '{{ item.delete|default(omit) }}'
    direction: '{{ item.direction|default(omit) }}'
    from_ip: '{{ item.from_ip|default(omit) }}'
    from_port: '{{ item.from_port|default(omit) }}'
    insert: '{{ item.insert|default(omit) }}'
    log: '{{ item.log|default(omit) }}'
    logging: '{{ item.logging|default(omit) }}'
    name: '{{ item.name|default(omit) }}'
    policy: '{{ item.policy|default(omit) }}'
    route: '{{ item.route|default(omit) }}'
    state: '{{ item.state|default(omit) }}'
    to_ip: '{{ item.to_ip|default(omit) }}'
    to_port: '{{ item.to_port|default(omit) }}'
  with_items: firewall_allowed_ports
  when: firewall_allowed_ports is defined

- name: enable ufw and block everything else
  ufw:
    state: enabled
    policy: deny